#!/usr/bin/env node
const process              = require("process");
const JSBuild              = require("./js_build");
const CSSBuild             = require("./css_build");
const vfl                  = require("./vfl");

process.chdir(__dirname);

console.log("cdbuild");
console.log("Build tool for CustoDesk assets");
console.log();

const PARTS = {
    css: CSSBuild,
    js: JSBuild
};

let g_parts = [];

for (let i = 2; i < process.argv.length; i++)
{
    if (!(argv[i] in PARTS))
    {
        console.log("Invalid part: " + process.argv[i]);
        console.log("Valid parts: " + Object.keys(PARTS).join(", "));
        return;
    }

    g_parts.push();
}

if (g_parts.length == 0)
{
    g_parts = Object.keys(PARTS);
}

for (const part of g_parts)
{
    console.log(`Building '${part}'...`);
    PARTS[part]();
}